### ISSUE TITLE
Optional CURL parameters for \WebDriver\WebDriver::session()

### ISSUE THREAD

**Issue by almostdaly** [instaclick/php-webdriver#53]
It would be awesome to get the session() method having the same parameters as the other library methods implementing the $extraOptions array so we can set a curl timeout (and any other desired curlopts) on the session start call.

We have an issue with our Selenium Hub/Grid whereby sessions will attempt to be started but hang/crash on the server which causes the tests to hang forever. Whilst I realise this needs to be resolved at the root cause, it still seems that this would be a useful feature in any case.

**Comment by gggeek** [comment]
Seems like I fell for thinking that I could set a proxy to be used between the webdriver and selenium, but it turns out the option available in behat.yml is used to tell the browser to use a proxy :-(

Being able to pass a set of default curl options which get injected for each call would probably allow me to achieve proxy support...

**Comment by aik099** [comment]
That would be great to have. I've also previously mentioned curl options in #51.
