### ISSUE TITLE
Use dependency injection

### ISSUE THREAD

**Issue by aik099** [instaclick/php-webdriver#73]
Right now the `pull` model (the service factory) is used instead of `push` model (dependency injection). The only service that is available right now is `CurlService` and it's used in 2 classes only:
- AbstractWebDriver
- SauceRest

Proposing to:
1. add an optional `$curlService` argument to constructor of mentioned classes
2. when not given use service factory to create it
3. add `$defaultOptions` constructor parameter to existing `CurlService` class, that would be stored as class property
4. the `CurlService::execute` method would merge `$defaultOptions` property with `$extraOptions` method argument to get final list of curl options for a request

This would both preserve BC and make replacement of CurlService straight forward.

**Comment by robocoder** [comment]
Linking to https://github.com/container-interop/fig-standards/blob/master/proposed/container.md

**Comment by stof** [comment]
you don't need PSR-11 for that. PSR-11 is not about standardizing dependency injection, but service location. For DI, you just need to get the dependency injected in the constructor instead of being instantiated internally (you can keep it optional and instantiated internally when not provided for ease of use)
