### ISSUE TITLE
Webdriver does not find any elements with newest Chrome

### ISSUE THREAD

**Issue by achudzinski** [instaclick/php-webdriver#92]
**Problem**

After last update of chrome and chromedriver, webdriver doesn't find elements on page anymore.

- chrome version: 75.0.3770.87 (Official Build) beta (64-bit) (mac)
- chromedriver: 75.0.3770.8
- selenium standalone server: 3.141.59

**Possible cause**
I've found out that in method `WebDriver\Container::webDriverElement` there is a check for `ELEMENT` key in `$value` array. But after checking content of that array I didn't find that key, instead there is a key in format `element-(something)`, eg.:

```array(1) {
    'element-6066-11e4-a52e-4f735466cecf' =>
    string(36) "e5707dbd-fc80-4bfb-aca3-ef2cf18ddf9d"
}
```

**Comment by Mramir-bounteous** [comment]
Can we get this issue reopened and resolved? I came across this issue with a Drupal project I am working on and I imagine there are many people in my situation with this issue. Currently behat/mink-selenium2-driver relies on instaclick/php-webdriver: ~1.1 but the above issue has been resolved in 2.x.

It would be great to backport the resolution to 1.x so that we don't need to rely on a stable 2.x to be released.
